homework week2
arash8877/hyf-homework pull request #4
Opened 2023-03-08 18:41 UTC by arash8877

Hi, Please review.

2023-03-09 11:09 UTC, YurijPaharev requested changes
Nicely done, please review some of the comments

2023-03-09 11:09 UTC, YurijPaharev commented on javascript/javascript1/week2/main.js
> +  }
You function is currently not returning anything, but it should by the task description

2023-03-09 11:09 UTC, YurijPaharev commented on javascript/javascript1/week2/main.js
> +}
You should not return console.log, you should return a value and then console.log it

2023-03-09 11:09 UTC, YurijPaharev commented on javascript/javascript1/week2/main.js
> +}
Try changing this function so that you just return the amount of element in the array

2023-03-09 11:09 UTC, YurijPaharev commented on javascript/javascript1/week2/main.js
> +  if (class07Students.length < 6 || studentName === "Queen") {
Is it a correct check? Because it only accepts 5 students + queen

2023-03-09 11:09 UTC, YurijPaharev commented on javascript/javascript1/week2/main.js
> +  }
You may want to read how .getDay works in order to simplify your function and change how weekDays are created

2023-03-10 10:16 UTC, arash8877 commented on javascript/javascript1/week2/main.js
> +  }
Thank you for the nice feedback. I have fixed the points.

2023-03-10 10:17 UTC, merged