homework js3
arash8877/hyf-homework pull request #5
Opened 2023-03-14 19:41 UTC by arash8877

Please review.

2023-03-14 20:20 UTC, YurijPaharev requested changes
I like that you are using more complex functions, please go through my comments for some insight

2023-03-14 20:20 UTC, YurijPaharev commented on javascript/javascript1/week3/app.js
> +names.splice(1, 1);
You should write a function that would be able to take in any name and remove it from list, right now you are just removing any item

2023-03-14 20:20 UTC, YurijPaharev commented on javascript/javascript1/week3/app.js
> +);
Very nice usage of reduce. You can actually write 0 directly, instead of storing it in a variable.

2023-03-14 20:20 UTC, YurijPaharev commented on javascript/javascript1/week3/app.js
> +  notes.map((item) => {
.map() is used to modify an array and return a new one, since you are not doing any of this you should use forEach() in this situation

2023-03-14 20:20 UTC, YurijPaharev commented on javascript/javascript1/week3/app.js
> +  activities.map((item) => (sum += item.duration));
Once again - better use forEach()

2023-03-14 20:20 UTC, YurijPaharev commented on javascript/javascript1/week3/app.js
> +const mostTimeSpent = activities.find((item) => item.duration === maxDuration);
Wonderful!

2023-03-15 18:36 UTC, arash8877 commented on javascript/javascript1/week3/app.js
> +const mostTimeSpent = activities.find((item) => item.duration === maxDuration);
Thank you for the nice comments. I have fixed them.

2023-03-15 18:37 UTC, merged